version: "2.3"
services:
  web:
    restart: always
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      redis:
        condition: service_healthy
  redis:
    restart: always
    image: "redis:alpine"
    volumes:
      - type: volume
        source: mydata
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 1s
    mem_limit: 500m
    cpus: 0.5 
volumes:
  mydata:
